# Generated by Django 3.1 on 2020-08-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='defaultName', max_length=50, unique=True)),
                ('model', models.CharField(default='product', max_length=50)),
                ('cost', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('img', models.ImageField(default='product_img/default.png', upload_to='product_img/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('telephone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AddTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('product_code', models.ForeignKey(db_column='code', default='code', on_delete=django.db.models.deletion.CASCADE, related_name='product_code', to='products.product')),
            ],
        ),
    ]
